#baseurl = ""
title = "Christian Z端nd"
copyright = "&copy; 2019 Christian Z端nd"
# theme = "academic"

enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
disqusShortname = ""
googleAnalytics = ""
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  color_theme = "zuendtheme"
  font = "flipfont"

  # Your details.
  name = "Christian Z端nd"
  role = "PhD Candidate"
  organizations = [ { name = "University of Zurich", url = "http://www.econ.uzh.ch" } ]

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "profile/zuend_uzh1.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  # email = "flip@example.org"
  email1 = "christian.zuend" # using cryptedmail
  email2 = "me" # using cryptedmail
  email3 = "com" # using cryptedmail
  address = "University of Zurich \n Bl端mlisalpstrass 10 \n 8006 Zurich \n Switzerland"
  phone = "+41 (0) 79 915 62 23"
  skype = "clzuend"
  # telegram = ""

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # Map provider:
  #   0: No map
  #   1: Google Maps
  map = 0
  map_api_key = ""
  latitude = "33.9745"
  longitude = "-117.3254"
  zoom = 17

  date_format = "Jan 2, 2006"
  time_format = "3:04 PM"

  reading_time = true
  comment_count = true
  section_pager = false
  math = false
  highlight = true
  highlight_languages = []
  sharing = true
  privacy_pack = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ['czuendlayout.css', 'cryptedmail.css', 'flip2018.css', 'flipaboutme.css', 'flipnav.css', 'slick.css', 'slick-theme.css', 'flipslick.css', 'ml-font.css']
  custom_js  = ['academic.js','jquery-2.2.0.min.js', 'slick.js', 'flipslick.js', 'clean.altmetric.js']

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
  #   translated.
  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section',  # 6
    'Job Market Paper',  # 7
  ]

  # FOOTER PARAMETERS
  footmark = "layout/icon_uzh_mz.png" # "layout/feynmanfooter.png"
  stacklogo = "" # "logo/uzh_logo_white.png"
  legalblurb = "" # "All opinions expressed here are my own and do not necessarily represent those of any other agencies or groups."

  # HEADER PARAMETERS
  watermark = "background/fancy_code.png"

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  # Email is added using cryptedmail_blind
  #[[params.social]]
  #  icon = "envelope"
  #  icon_pack = "fa"
  #  link = "mailto:christian.zuend@me.com"
  #  cv = true

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?view_op=list_works&hl=en&user=rB3BXV8AAAAJ"
    cv = true

  [[params.social]]
    icon = "orcid"
    icon_pack = "ai"
    link = "https://orcid.org/0000-0002-4436-4071"
    cv = true

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "https://github.com/clzuend"
    cv = true

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    link = "www.linkedin.com/in/christian-zuend"
    cv = true

# maybe add Arxiv and twitter back, maybe add linkedin ...

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "CV"
  url = "#CV"
  weight = 2

[[menu.main]]
  name = "Research"
  url = "#projects"
  weight = 3

[[menu.main]]
  name = "Publications"
  url = "#featured"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  
# Comments.
[params.comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  engine = 0

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true, project = true, publication = true, talk = true}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)

# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"
